version: "3"
services:
  uiapp:
    image: roshan/trailer-ui:latest
    container_name: uiapp
    restart: always
    environment:
      - REDIS_ENV=false
      - TRAILER_API_HOST=apiapp
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - 8080:8080
    links:
      - apiapp

  apiapp:
    image: roshan/film-trailer:latest
    container_name: apiapp
    restart: always
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 3000:3000
    links:
      - redis
  redis:
    image: redis:4.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379