version: "3"
services:
  uiapp:
    image: roshan/trailer-ui:latest
    container_name: uiapp
    restart: always
    environment:
      - REDIS_ENV=false
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - 8080:8080
    links:
      - apiapp

  apiapp:
    image: roshan/film-trailer:latest
    container_name: apiapp
    restart: always
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - 3000:3000
  redis:
    image: redis:4.0
    restart: always
    ports:
      - 6379:6379
